METS-Programme/esm-ugandaemr-core

packages/esm-ugandaemr-app/src/ugandaemr-configuration-overrrides.json
only maintain female and male as the gender options upon patient registration.
=> Remove the "other" option from gender upon patient registration

packages/esm-family-health-app/src/index.ts, packages/esm-family-health-app/src/routes.json, packages/esm-outpatient-app/src/index.ts, packages/esm-outpatient-app/src/routes.json, packages/esm-patient-queues-app/src/index.ts, packages/esm-patient-queues-app/src/routes.json, packages/esm-ugandaemr-app/src/index.ts, packages/esm-ugandaemr-app/src/routes.json, yarn.lock
=> ft : migrate to v5

packages/esm-ugandaemr-app/src/ugandaemr-configuration-overrrides.json
=> fix : change active queue icon

packages/esm-patient-queues-app/src/active-visits/active-visits-tab.component.tsx, packages/esm-patient-queues-app/src/active-visits/active-visits-table.component.tsx, packages/esm-patient-queues-app/src/active-visits/patient-queues.resource.ts, packages/esm-patient-queues-app/src/home.component.tsx, packages/esm-patient-queues-app/src/patient-search/visit-form/visit-form.component.tsx
ft : add priority level columns in visits table
=> ft :  priority level column

package.json, packages/esm-patient-queues-app/src/active-visit-patient-reception/active-visits-reception.resource.ts, packages/esm-patient-queues-app/src/active-visits/active-visits-tab.component.tsx, packages/esm-patient-queues-app/src/active-visits/active-visits-table.component.tsx, packages/esm-patient-queues-app/src/active-visits/active-visits-table.resource.ts, packages/esm-patient-queues-app/src/active-visits/change-status-dialog.component.tsx, packages/esm-patient-queues-app/src/active-visits/pick-patient-dialog.component.tsx, packages/esm-patient-queues-app/src/index.ts, packages/esm-patient-queues-app/src/patient-queue-metrics/clinic-metrics.component.tsx, packages/esm-patient-queues-app/src/patient-queue-metrics/clinic-metrics.resource.tsx, packages/esm-patient-queues-app/src/patient-search/hooks/useQueueRooms.tsx, packages/esm-patient-queues-app/src/patient-search/visit-form/visit-form.component.tsx, packages/esm-patient-queues-app/src/queue-entry-table-components/pick-patient-queue-entry-menu.component.tsx, packages/esm-patient-queues-app/src/routes.json, packages/esm-patient-queues-app/src/transition-queue-entry/transition-queue-entry-dialog.component.tsx, packages/esm-patient-queues-app/src/types/index.ts
- add move to next queue dialog
=> (chore) :  clean up queue workflows 

packages/esm-patient-queues-app/src/active-visit-patient-reception/active-visits-reception-table.component.tsx, packages/esm-patient-queues-app/src/active-visit-patient-reception/active-visits-reception.resource.ts, packages/esm-patient-queues-app/src/active-visits/patient-queues.resource.ts, packages/esm-patient-queues-app/src/queue-entry-table-components/pick-patient-queue-entry-menu.component.tsx
=> fix : change move icon to notifications icon

packages/esm-ugandaemr-app/src/routes.json
- fix remove facility and hie dashboards
=> fix : remove hie and facility dashboard

packages/esm-ipd-app/src/routes.json, packages/esm-patient-queues-app/src/active-visits/change-status-dialog.component.tsx, packages/esm-patient-queues-app/src/active-visits/pick-patient-dialog.component.tsx, packages/esm-patient-queues-app/src/constants.ts, packages/esm-patient-queues-app/src/home.component.tsx, packages/esm-tb-app/src/routes.json, packages/esm-ugandaemr-app/src/config-schema.ts, packages/esm-ugandaemr-app/src/routes.json, packages/esm-ugandaemr-app/src/ugandaemr-configuration-overrrides.json
- fix move to next
- update privileges
=> fix : fix clinician workflow

packages/esm-patient-queues-app/src/routes.json, packages/esm-radiology-app/src/routes.json, packages/esm-ugandaemr-app/src/pages/system-info/system-info.resources.tsx
- change dashboard item ordering.
=> fix: change queue and radiology dashboard order

packages/esm-patient-queues-app/src/active-visits/active-visits-table.component.tsx
-  add current visit expanded queue tab
=> fix: add current visit expanded tab

packages/esm-patient-queues-app/src/active-visit-patient-reception/active-visits-reception-table.component.tsx, packages/esm-patient-queues-app/src/active-visit-patient-reception/active-visits-reception.resource.ts, packages/esm-patient-queues-app/src/active-visits/active-visits-table.component.tsx, packages/esm-patient-queues-app/src/active-visits/patient-queues.resource.ts
=> fix:  update-queue-api

packages/esm-patient-queues-app/src/active-visit-patient-reception/active-visits-reception-table.component.tsx, packages/esm-patient-queues-app/src/active-visit-patient-reception/active-visits-reception.resource.ts, packages/esm-patient-queues-app/src/active-visits/active-visits-table.component.tsx, packages/esm-patient-queues-app/src/active-visits/change-status-dialog.component.tsx, packages/esm-patient-queues-app/src/active-visits/patient-queues.resource.ts
=> fix: fix provider error

packages/esm-patient-queues-app/src/patient-queue-header/patient-queue-header.component.tsx, packages/esm-patient-queues-app/src/patient-queue-header/patient-queue-header.scss
- add clinic to patient queue header
=> ft : add parent location

packages/esm-patient-queues-app/src/active-visits/change-status-dialog.component.tsx, packages/esm-patient-queues-app/src/active-visits/patient-queues.resource.ts, packages/esm-patient-queues-app/src/patient-queue-metrics/clinic-metrics.component.tsx, packages/esm-patient-queues-app/src/patient-queue-metrics/metrics-card.component.tsx
=> ft : set up serving tile

packages/esm-patient-queues-app/src/active-visits/change-status-dialog.component.tsx
=> fix:  rename title to Queue to next service area

packages/esm-ugandaemr-app/src/constants.ts, packages/esm-ugandaemr-app/src/pages/system-info/system-info.component.tsx, packages/esm-ugandaemr-app/src/pages/system-info/system-info.resources.tsx
=> Fix system info page load error

packages/esm-patient-queues-app/src/active-visit-patient-reception/active-visits-reception.resource.ts, packages/esm-patient-queues-app/src/active-visits-print/patient-queue-details-table.component.tsx, packages/esm-patient-queues-app/src/active-visits/active-visits-table.resource.ts, packages/esm-patient-queues-app/src/active-visits/change-status-dialog.component.tsx, packages/esm-patient-queues-app/src/active-visits/patient-queues.resource.ts, packages/esm-patient-queues-app/src/active-visits/pick-patient-dialog.component.tsx
- remove provider notifications
=> fix : UI for queues

packages/esm-patient-queues-app/src/active-visit-patient-reception/active-visits-reception.resource.ts, packages/esm-patient-queues-app/src/active-visits-print/patient-queue-details-table.component.tsx, packages/esm-patient-queues-app/src/active-visits/active-visits-table.resource.ts, packages/esm-patient-queues-app/src/active-visits/change-status-dialog.component.tsx, packages/esm-patient-queues-app/src/active-visits/patient-queues.resource.ts, packages/esm-patient-queues-app/src/active-visits/pick-patient-dialog.component.tsx, packages/esm-ugandaemr-app/src/config-schema.ts, packages/esm-ugandaemr-app/src/pages/system-info/facility-modal.component.tsx, packages/esm-ugandaemr-app/src/pages/system-info/system-info.resources.ts, packages/esm-ugandaemr-app/src/pages/system-info/types.ts
=> Fix/ update facility registry url

packages/esm-patient-queues-app/src/active-visit-patient-reception/active-visits-reception-table.component.tsx, packages/esm-patient-queues-app/src/active-visits/active-visits-table.component.tsx
https://metsprogramme.atlassian.net/browse/U4X-299
=> remove priority level and level from queues table

packages/esm-patient-queues-app/src/active-visits/active-visits-tab.component.tsx
https://metsprogramme.atlassian.net/browse/U4X-300
=> remove serving from clinician and triage

packages/esm-patient-queues-app/src/active-visits/active-visits-table.component.tsx, packages/esm-patient-queues-app/src/active-visits/active-visits-table.resource.ts, packages/esm-patient-queues-app/src/active-visits/change-status-dialog.component.tsx, packages/esm-patient-queues-app/src/active-visits/patient-queues.resource.ts, packages/esm-patient-queues-app/src/add-patient-toqueue/add-patient-toqueue-dialog.component.tsx, packages/esm-patient-queues-app/src/patient-search/visit-form/visit-form.component.tsx, packages/esm-patient-queues-app/src/post-submission-actions/ipd-admission-submission-action.ts, packages/esm-patient-queues-app/src/post-submission-actions/lab-admission-submission-action.ts, packages/esm-patient-queues-app/src/post-submission-actions/medications-admission-submission-action.ts, packages/esm-patient-queues-app/src/post-submission-actions/radiology-admission-submission-action.ts
https://metsprogramme.atlassian.net/browse/U4X-301
=> U4X-301 : Add provider tag showing the provider's name in the datatable

packages/esm-patient-queues-app/src/active-visits/active-visits-table.component.tsx, packages/esm-patient-queues-app/src/active-visits/notes-action-menu.components.tsx, packages/esm-patient-queues-app/src/active-visits/notes-dialog.component.tsx, packages/esm-patient-queues-app/src/active-visits/patient-queues.resource.ts, packages/esm-patient-queues-app/src/index.ts, packages/esm-patient-queues-app/src/patient-queue-metrics/clinic-metrics.component.tsx, packages/esm-patient-queues-app/src/routes.json
https://metsprogramme.atlassian.net/browse/U4X-314
https://github.com/METS-Programme/esm-ugandaemr-core/assets/24471994/73e55a47-ee21-4fa4-9338-267087550136
=> U4X-314 : Add visibility of notes taken somewhere in the patient summary chart

packages/esm-ugandaemr-app/src/ugandaemr-configuration-overrrides.json
https://metsprogramme.atlassian.net/browse/U4X-318
=> U4X-318: Configure and restrict access to patient search and add action

packages/esm-patient-queues-app/src/active-visits-print/patient-queue-details-table.component.tsx
https://metsprogramme.atlassian.net/browse/U4X-319
=> Change Entry point and Attendant

packages/esm-patient-queues-app/src/patient-search/visit-form/visit-form.component.tsx
https://metsprogramme.atlassian.net/browse/U4X-332
=> Add back patient details on check overlay

packages/esm-patient-queues-app/src/active-visits-print/active-visits-print.component.tsx
https://metsprogramme.atlassian.net/browse/U4X-374
=> U4X-374 Attaching patient uic in the queue barcode

packages/esm-patient-queues-app/src/active-visits/active-visits-tab.component.tsx, packages/esm-patient-queues-app/src/active-visits/active-visits-table.component.tsx, packages/esm-patient-queues-app/src/constants.ts
https://metsprogramme.atlassian.net/browse/U4X-335
=> U4X-335-Fix-Clinician-workflow

packages/esm-ugandaemr-app/src/index.ts, packages/esm-ugandaemr-app/src/routes.json
=> Removing the facility code alert notification to test the chatbot functionality

packages/esm-patient-queues-app/src/config-schema.ts, packages/esm-patient-queues-app/src/constants.ts, packages/esm-patient-queues-app/src/patient-queue-metrics/clinic-metrics.component.tsx, packages/esm-patient-queues-app/src/patient-queue-metrics/clinic-metrics.resource.tsx, packages/esm-patient-queues-app/src/types/index.ts
=> U4X-340 : Fix no of expected appointments

package.json, packages/esm-patient-queues-app/src/active-visit-patient-reception/active-visits-reception-table.component.tsx, packages/esm-patient-queues-app/src/active-visits/patient-queues.resource.ts, packages/esm-patient-queues-app/src/patient-info/contact-details.component.tsx, packages/esm-patient-queues-app/src/patient-search/visit-form/queue.resource.ts, packages/esm-patient-queues-app/src/patient-search/visit-form/visit-form.component.tsx, packages/esm-patient-queues-app/src/queue-patient-linelists/queue-linelist.resource.tsx, packages/esm-patient-queues-app/src/types/index.ts, packages/esm-tb-app/src/program-action-button/program-action-button.component.tsx, yarn.lock
Screenshots
https://github.com/METS-Programme/esm-ugandaemr-core/assets/24471994/3fcbd61c-7f2d-4fb4-b0da-73e7fca762b6
https://metsprogramme.atlassian.net/browse/U4X-400
=> U4X-400: Show providers only available for the selected service location

packages/esm-patient-queues-app/src/patient-queue-metrics/clinic-metrics.component.tsx, packages/esm-patient-queues-app/src/patient-queue-metrics/clinic-metrics.resource.tsx, packages/esm-ugandaemr-app/package.json
https://github.com/METS-Programme/esm-ugandaemr-core/assets/89844768/d0bb5bd3-dd91-41ff-bcf6-894557c5f05e
https://metsprogramme.atlassian.net/browse/U4X-401
=> Aligning the check-in Tile tagged to a specific location

packages/esm-patient-queues-app/src/active-visits/active-visits-table.component.tsx, packages/esm-patient-queues-app/src/helpers/functions.ts
https://github.com/METS-Programme/esm-ugandaemr-core/assets/89844768/8798c909-d47c-4b15-a6cc-b2f5af7179de
=> Filtering patients by adding a color tag for the particular provider logged in

packages/esm-patient-queues-app/src/active-visit-patient-reception/active-visits-reception-table.component.tsx, packages/esm-patient-queues-app/src/active-visits/active-visits-tab.component.tsx, packages/esm-patient-queues-app/src/active-visits/active-visits-table.component.tsx, packages/esm-patient-queues-app/src/active-visits/active-visits-table.test.tsx, packages/esm-patient-queues-app/src/active-visits/change-status-dialog.component.tsx, packages/esm-patient-queues-app/src/active-visits/pick-patient-dialog.component.tsx, packages/esm-patient-queues-app/src/patient-queue-metrics/clinic-metrics.resource.tsx, packages/esm-patient-queues-app/src/patient-search/visit-form/visit-form.component.tsx, packages/esm-patient-queues-app/src/queue-entry-table-components/pick-patient-queue-entry-menu.component.tsx
https://metsprogramme.atlassian.net/browse/U4X-407
=> Enable another loggedIn user to pick a patient in a patient queues

packages/esm-patient-queues-app/src/patient-queue-metrics/clinic-metrics.component.tsx, packages/esm-patient-queues-app/src/patient-queue-metrics/clinic-metrics.resource.tsx, packages/esm-patient-queues-app/src/patient-queue-metrics/metrics-card.component.tsx, packages/esm-patient-queues-app/src/patient-queue-metrics/metrics-card.scss
Screenshots
- Add patient service point statistics on the reception 
- https://metsprogramme.atlassian.net/browse/U4X-406
=> U4X:402 :No. of Currently being Served in the different service points in the clinic

packages/esm-patient-queues-app/src/active-visits/active-visits-tab.component.tsx, packages/esm-patient-queues-app/src/active-visits/active-visits-table.component.tsx
https://github.com/METS-Programme/esm-ugandaemr-core/assets/89844768/6ce7b922-b314-4ebe-bd25-a462b197a12e
https://metsprogramme.atlassian.net/browse/U4X-408
=> Filtering out finished patients from the in queue table, Sorting patients with status picked to appear at the bottom of the data table

packages/esm-patient-queues-app/src/active-visits/active-visits-tab.component.tsx, packages/esm-patient-queues-app/src/active-visits/change-status-move-to-next-dialog.component.tsx, packages/esm-patient-queues-app/src/config-schema.ts, packages/esm-patient-queues-app/src/lab-results/lab-results.component.tsx, packages/esm-patient-queues-app/src/lab-results/lab-results.resource.ts, packages/esm-patient-queues-app/src/lab-results/lab-results.scss, packages/esm-patient-queues-app/src/transition-queue-entry/transition-queue-entry-dialog.component.tsx, packages/esm-patient-queues-app/src/utils/utils.ts
- add tab to view investigations
- add badges to indicate returns returned
- Screenshots
-https://metsprogramme.atlassian.net/browse/U4X-410
=> U4X-410 : Implement a clinician workflow for patients who are waiting for results while in the queue

packages/esm-patient-queues-app/src/lab-results/lab-results.component.tsx
=> fix clinician bug

packages/esm-patient-queues-app/src/active-visits/active-visits-tab.component.tsx, packages/esm-patient-queues-app/src/active-visits/active-visits-table.scss, packages/esm-patient-queues-app/src/lab-results/lab-results.component.tsx
This Pr fixes lag in the patient queue module
=> Fix create badge

packages/esm-patient-queues-app/src/active-visits/active-visits-tab.component.tsx, packages/esm-patient-queues-app/src/active-visits/active-visits-table.scss
This PR shows patients currently waiting for results under investigations tab in the patient queues
=> (feat) create badge on the investigations tab to show number of patients waiting for results

packages/esm-patient-queues-app/src/active-visits/active-visits-tab.component.tsx, packages/esm-patient-queues-app/src/lab-results/lab-results.component.tsx
=> fix pick  up of patient lag

README.md
=> (docs) Update status badge in README

packages/esm-patient-queues-app/src/active-visits/active-visits-table.component.tsx, packages/esm-patient-queues-app/src/active-visits/change-status-dialog.component.tsx, packages/esm-patient-queues-app/src/active-visits/change-status-move-to-next-dialog.component.tsx, packages/esm-patient-queues-app/src/patient-queue-metrics/clinic-metrics.component.tsx, packages/esm-patient-queues-app/src/patient-queue-metrics/clinic-metrics.resource.tsx
This PR fixes queue statistics flickering
https://metsprogramme.atlassian.net/browse/U4X-456
=> (bug ) U4X-456 : fix queue statistics flickering

packages/esm-family-health-app/src/routes.json, packages/esm-hiv-app/src/routes.json, packages/esm-ipd-app/src/routes.json, packages/esm-outpatient-app/src/routes.json, packages/esm-patient-queues-app/src/routes.json, packages/esm-radiology-app/src/routes.json, packages/esm-tb-app/src/routes.json, packages/esm-theatre-app/src/routes.json, packages/esm-ugandaemr-app/src/routes.json
This PR fixes the fhir2 module version
https://metsprogramme.atlassian.net/browse/U4X-462
=>  U4X-462 :  Fix fhir2 backend dependency module error

packages/esm-ugandaemr-app/src/index.ts, packages/esm-ugandaemr-app/src/menu-app-items/despensing-app-menu-item/dispensing-app-menu-item.component.tsx, packages/esm-ugandaemr-app/src/menu-app-items/despensing-app-menu-item/dispensing-app-menu-item.scss, packages/esm-ugandaemr-app/src/routes.json
This PR adds Dispensing app to the menu item app
https://metsprogramme.atlassian.net/browse/U4X-464
=> U4X-464:add dispensing app on menu item

packages/esm-patient-queues-app/src/dashboard.meta.ts, packages/esm-patient-queues-app/src/home.component.tsx, packages/esm-patient-queues-app/src/index.ts, packages/esm-patient-queues-app/src/queue-clinical-room-home.component.tsx, packages/esm-patient-queues-app/src/queue-reception-home.component.tsx, packages/esm-patient-queues-app/src/queue-triage-home.component.tsx, packages/esm-patient-queues-app/src/root.component.tsx, packages/esm-patient-queues-app/src/routes.json
This PR separates the patient queue pages of triage,reception and clinical room
https://github.com/METS-Programme/esm-ugandaemr-core/assets/24471994/a9afe692-516a-485b-9546-6e9f92837c57
https://metsprogramme.atlassian.net/browse/U4X-467
=> U4X-467 :  Create separate Patient-Queues UIs i.e Triage,Reception and Clinical-Room

packages/esm-ugandaemr-app/src/ugandaemr-configuration-overrrides.json
This PR Adds validation to telephone number on registration
https://github.com/METS-Programme/esm-ugandaemr-core/assets/5467866/a91574ca-cb54-46b5-8482-2330955af606
https://metsprogramme.atlassian.net/browse/U4X-473
=> U4X-473:Add validation to telephone number

packages/esm-ugandaemr-app/src/ugandaemr-configuration-overrrides.json
This PR Adds patient alternative number on registration
https://github.com/METS-Programme/esm-ugandaemr-core/assets/5467866/b92b9522-d46f-4e86-aa47-be4e560f01af
https://metsprogramme.atlassian.net/browse/U4X-469
=> U4X-469: Add patient alternative number on registration

packages/esm-patient-queues-app/src/visit-form/visit-form.component.tsx
This PR fixes show current loggedIn location in next service point
=> fix show all location inclusive of your current

packages/esm-ugandaemr-app/src/ugandaemr-configuration-overrrides.json
This PR adds a configuration to add color codes for MUAC
https://metsprogramme.atlassian.net/browse/U4X-472
=> U4X-472: Add color codes to MUAC

packages/esm-ugandaemr-app/src/ugandaemr-configuration-overrrides.json
=> Add Dispensing on config

packages/esm-patient-queues-app/src/active-visit-patient-reception/active-visits-reception-table.component.tsx, packages/esm-patient-queues-app/src/active-visit-patient-reception/active-visits-reception.scss, packages/esm-patient-queues-app/src/active-visits/active-visits-table.component.tsx
This PR fixes the pagination on the queue tables for both the clinician and the reception users
https://github.com/METS-Programme/esm-ugandaemr-core/assets/24471994/aedbf56a-ad92-4f7e-a67c-27c19d14d069
https://metsprogramme.atlassian.net/browse/U4X-544
=>  U4X-544 : The pagination on the  queue tables doesn’t work as expected

packages/esm-care-panel-app/src/care-panel/care-panel.component.tsx, packages/esm-care-panel-app/src/care-panel/care-panel.scss, packages/esm-care-panel-app/src/config-schema.ts, packages/esm-care-panel-app/src/constants.ts, packages/esm-care-panel-app/src/dsdm-history/dsdm-history.component.tsx, packages/esm-care-panel-app/src/dsdm-history/dsdm-history.scss, packages/esm-care-panel-app/src/hooks/usePatientPrograms.ts, packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.tsx, packages/esm-care-panel-app/src/regimen-history/regimen-history.component.tsx, packages/esm-care-panel-app/src/types/index.ts
https://metsprogramme.atlassian.net/browse/U4X-539
https://github.com/METS-Programme/esm-ugandaemr-core/assets/89844768/3c49c966-5920-4bbe-8cd2-99b6bf174fd8
=> U4X-539: Adding patient DSDM History & Regimen History

packages/esm-care-panel-app/src/care-panel/care-panel.component.tsx, packages/esm-care-panel-app/src/care-panel/care-panel.scss, packages/esm-care-panel-app/src/program-enrollment/program-enrollment.component.tsx, packages/esm-care-panel-app/src/program-enrollment/program-enrollment.scss
=> Adding CSS style to the care panel

packages/esm-care-panel-app/src/care-panel/care-panel.component.tsx, packages/esm-care-panel-app/src/config-schema.ts, packages/esm-care-panel-app/src/program-enrollment/program-enrollment-hiv.component.tsx, packages/esm-care-panel-app/src/program-enrollment/program-enrollment.resource.ts, packages/esm-care-panel-app/src/program-enrollment/program-enrollment.scss, packages/esm-care-panel-app/src/types/index.ts
https://github.com/METS-Programme/esm-ugandaemr-core/assets/89844768/b85e2335-cf84-4a6f-8ee2-e0e5e8fbdfeb
https://metsprogramme.atlassian.net/browse/U4X-566
=> U4X-566: Adding Patient TPT Details to the Care Panel

packages/esm-care-panel-app/src/dsdm-history/dsdm-history.component.tsx, packages/esm-care-panel-app/src/hooks/usePatientPrograms.ts
https://github.com/METS-Programme/esm-ugandaemr-core/assets/89844768/fe32000a-0e18-49c5-b766-96a043390d6f
https://metsprogramme.atlassian.net/browse/U4X-608
=> U4X-608: Change DSDM implementation to use program workflows

packages/esm-patient-queues-app/src/active-visits/change-status-dialog.component.tsx
https://github.com/METS-Programme/esm-ugandaemr-core/assets/89844768/3a565313-eb6d-45d4-a610-1c09bd62ba2a
https://metsprogramme.atlassian.net/browse/U4X-637
=> U4X-637: Adding a toast notification on either picking or moving back a patient back in the queue

packages/esm-patient-programs-app/package.json, packages/esm-ugandaemr-app/src/createDashboardLink.tsx, packages/esm-ugandaemr-app/src/index.ts, packages/esm-ugandaemr-app/src/routes.json, yarn.lock
https://github.com/METS-Programme/esm-ugandaemr-core/assets/89844768/3864bbfb-3308-410e-b11d-3c785997303e
https://metsprogramme.atlassian.net/browse/U4X-653
=> U4X-653: Adding pharmacy on the side nav menu

packages/esm-ugandaemr-app/src/ugandaemr-configuration-overrrides.json
This PR moves special categories section to the point of registration so that a client can be categorised irrespective of the the service being sought for. this willl allow to multile usage in different service areas away from HIV
Uploading Screen Recording 2024-06-13 at 10.52.04.mov…
https://metsprogramme.atlassian.net/browse/U4X-596
=> U4X-596: Special Categories Implementation

packages/esm-patient-queues-app/src/root.component.tsx, packages/esm-patient-queues-app/src/visit-form/visit-form.component.tsx
=> (chore) : core navigation clean up

packages/esm-ugandaemr-app/src/custom-expressions/custom-expressions.ts, packages/esm-ugandaemr-app/src/index.ts
https://metsprogramme.atlassian.net/browse/U4X-676
=> Custom expression for calc months on ART and numeric datatype logic

packages/esm-ugandaemr-app/src/index.ts, packages/esm-ugandaemr-app/src/ugandaemr-configuration-overrrides.json
The address where a specific individual can be found or contacted.
=> U4X-667: Add directions to residence on patient registration

packages/esm-ugandaemr-app/src/config-ugandaemr/frontend-config.json
https://metsprogramme.atlassian.net/browse/U4X-701
=> U4X-701: Fix issues in frontend.config file introduced by merge issues

packages/esm-patient-queues-app/src/active-visits/active-visits-table.component.tsx, packages/esm-patient-queues-app/src/active-visits/active-visits-table.resource.ts, packages/esm-patient-queues-app/src/active-visits/change-status-dialog.component.tsx, packages/esm-patient-queues-app/src/active-visits/change-status-move-to-next-dialog.component.tsx, packages/esm-patient-queues-app/src/active-visits/edit-action-menu.components.tsx, packages/esm-patient-queues-app/src/active-visits/notes-action-menu.components.tsx, packages/esm-patient-queues-app/src/active-visits/pick-patient-dialog.component.tsx, packages/esm-patient-queues-app/src/active-visits/view-action-menu.components.tsx, packages/esm-patient-queues-app/src/queue-entry-table-components/actions-menu.component.tsx, packages/esm-patient-queues-app/src/queue-entry-table-components/pick-patient-queue-entry-menu.component.tsx, packages/esm-patient-queues-app/src/visit-form/queue.resource.ts
=> fix : remove provider reloads

packages/esm-ugandaemr-app/src/custom-expressions/custom-apis.ts, packages/esm-ugandaemr-app/src/custom-expressions/custom-expressions.ts, packages/esm-ugandaemr-app/src/index.ts
Add Custom datasource for CDDP Refill points
https://metsprogramme.atlassian.net/browse/U4X-717
=> Add custom datasource for dsdm refill points

packages/esm-patient-queues-app/src/active-visit-patient-reception/active-visits-reception-table.component.tsx, packages/esm-patient-queues-app/src/active-visits/active-visits-table.component.tsx
https://metsprogramme.atlassian.net/browse/U4X-742
=> (feat) U4X-742 : Order queues in descending order basing on date of creation

packages/esm-patient-queues-app/src/active-visits/patient-queues.resource.ts
https://metsprogramme.atlassian.net/browse/U4X-854
=> U4X-854: Fixing the wait time under completion tab to stop counting

.github/workflows/node.js.yml
This PR updates the artifacts upload action plugin
=> update artifacts upload

.github/workflows/node.js.yml
=> clear cache

.github/workflows/node.js.yml
=> update to fix versioning in ci

.github/workflows/node.js.yml
=> update lerna script

.github/workflows/node.js.yml
=> fix auth script ci

packages/esm-ugandaemr-app/src/app-menu/app-search-bar/app-search-bar.component.tsx, packages/esm-ugandaemr-app/src/app-menu/app-search-bar/app-search-bar.scss, packages/esm-ugandaemr-app/src/app-menu/app-search-icon/app-search-icon.component.tsx, packages/esm-ugandaemr-app/src/app-menu/app-search-icon/app-search-icon.scss, packages/esm-ugandaemr-app/src/app-menu/app-search-overlay/app-search-overlay.component.tsx, packages/esm-ugandaemr-app/src/index.ts, packages/esm-ugandaemr-app/src/overlay/overlay.scss, packages/esm-ugandaemr-app/src/overlay/overlay.tsx, packages/esm-ugandaemr-app/src/routes.json
=> Add app menu to  core

packages/esm-ugandaemr-app/src/index.ts, packages/esm-ugandaemr-app/src/routes.json
This PR adds launch button to primary navigation instead of the overlay
=> show button to launch app menu

packages/esm-care-panel-app/package.json, packages/esm-patient-flags-app/package.json, packages/esm-patient-queues-app/package.json, packages/esm-ugandaemr-app/package.json, packages/esm-ugandaemr-app/src/app-menu/app-search-icon/app-search-icon.component.tsx, packages/esm-ugandaemr-app/src/app-menu/app-search-overlay/app-search-overlay.component.tsx
This PR bumps the esm-framework
=> bump framework

packages/esm-care-panel-app/package.json, packages/esm-patient-flags-app/package.json, packages/esm-patient-queues-app/package.json, packages/esm-ugandaemr-app/package.json, yarn.lock
=> Bump-framework

packages/esm-ugandaemr-app/src/app-menu/app-search-bar/app-search-bar.component.tsx
This PR tries to update implementation of extensions on the app-menu
=> refactor app menu implementation

packages/esm-ugandaemr-app/src/app-menu/app-search-icon/app-search-icon.component.tsx, packages/esm-ugandaemr-app/src/app-menu/app-search-overlay/app-search-overlay.component.tsx
This PR refactors app icon code snippet to remove unnecessary code.
=> Remove unnecessary app icon code

packages/esm-ugandaemr-app/src/app-menu/app-search-icon/app-search-icon.component.tsx
This PR fixes the styling of the
=> fix styling

packages/esm-ugandaemr-app/src/app-menu/app-search-icon/app-search-icon.component.tsx, packages/esm-ugandaemr-app/src/app-menu/app-search-overlay/app-search-overlay.component.tsx
=> fix styling update

packages/esm-ugandaemr-app/src/app-menu/app-search-bar/app-search-bar.component.tsx, packages/esm-ugandaemr-app/src/overlay/overlay.scss
=> fix overlay

packages/esm-ugandaemr-app/src/app-menu/app-search-bar/app-search-bar.component.tsx
=> Fix-overlay

packages/esm-ugandaemr-app/src/dashboard.meta.tsx, packages/esm-ugandaemr-app/src/index.ts, packages/esm-ugandaemr-app/src/routes.json, packages/esm-ugandaemr-app/src/views/hiv/hct/general-counselling/general-conselling-config.json, packages/esm-ugandaemr-app/src/views/hiv/hct/general-counselling/general-counselling-summary.component.tsx
This PR adds general counselling view in the clinical views
=> create general counselling

packages/esm-ugandaemr-app/src/dashboard.meta.tsx, packages/esm-ugandaemr-app/src/index.ts, packages/esm-ugandaemr-app/src/routes.json, packages/esm-ugandaemr-app/src/views/hiv/hct/family-tracking/family-tracking-config.json, packages/esm-ugandaemr-app/src/views/hiv/hct/family-tracking/family-tracking-summary.component.tsx, packages/esm-ugandaemr-app/src/views/hiv/hct/general-counselling/general-conselling-config.json, packages/esm-ugandaemr-app/src/views/hiv/hct/patient-summary/patient-summary-baseline-information-config.json, packages/esm-ugandaemr-app/src/views/hiv/hct/patient-summary/patient-summary-hiv-monitoring-config.json, packages/esm-ugandaemr-app/src/views/hiv/hct/patient-summary/patient-summary-summary.component.tsx, packages/esm-ugandaemr-app/src/views/hiv/hct/patient-summary/patient-summary-tpt-config.json, packages/esm-ugandaemr-app/src/views/hiv/hct/patient-summary/patient-summary-visit-config.json, packages/esm-ugandaemr-app/src/views/hiv/hct/patient-transfers/patient-transfers-config.json, packages/esm-ugandaemr-app/src/views/hiv/hct/patient-transfers/patient-transfers-summary.component.tsx, packages/esm-ugandaemr-app/src/views/hiv/hct/treatment-regimen/treatment-regimen-config.json, packages/esm-ugandaemr-app/src/views/hiv/hct/treatment/treatment-config.json, packages/esm-ugandaemr-app/src/views/hiv/hct/treatment/treatment-summary.component.tsx
This PR adds the rest of the remaining dashboards
=> add the remaing dashboards

packages/esm-care-panel-app/package.json, packages/esm-care-panel-app/src/dashboard.meta.ts, packages/esm-ugandaemr-app/package.json, packages/esm-ugandaemr-app/src/dashboard.meta.tsx, packages/esm-ugandaemr-app/src/index.ts, yarn.lock
This PR fixes failure to add an encounter using the clinical views.
=> fix add form button failure

packages/esm-ugandaemr-app/src/dashboard.meta.tsx, packages/esm-ugandaemr-app/src/index.ts, packages/esm-ugandaemr-app/src/routes.json, packages/esm-ugandaemr-app/src/views/eid/eid-config.json, packages/esm-ugandaemr-app/src/views/eid/eid.component.tsx, packages/esm-ugandaemr-app/src/views/hiv/hct/patient-transfers/patient-transfers-config.json, packages/esm-ugandaemr-app/src/views/hiv/hct/treatment/treatment-config.json, packages/esm-ugandaemr-app/src/views/hiv/hps/vmmc/vmm-services-config.json, packages/esm-ugandaemr-app/src/views/tb/dr/dr-tb-config.json, packages/esm-ugandaemr-app/src/views/tb/ds/ds-tb-config.json
https://metsprogramme.atlassian.net/browse/U4X-897
=> U4X-897: Fixing broken forms on clinical views

packages/esm-patient-queues-app/src/config/privileges.ts
U4X-914-fix-the-triage-and-clinician-queue-table
=> UX-914: Fix queue and clinician tables

packages/esm-patient-queues-app/src/active-visits/change-status-dialog.component.tsx, packages/esm-patient-queues-app/src/active-visits/change-status-move-to-next-dialog.component.tsx, packages/esm-patient-queues-app/src/active-visits/queue-table-move-to-next-dialog.component.tsx
This PR fixes the pick patient crash
=> fix pick patient crush

lerna.json, packages/esm-care-panel-app/package.json, packages/esm-patient-flags-app/package.json, packages/esm-patient-queues-app/package.json, packages/esm-ugandaemr-app/package.json
=> bump versions

packages/esm-ugandaemr-app/src/views/hiv/hct/family-tracking/family-tracking-config.json, packages/esm-ugandaemr-app/src/views/hiv/hct/patient-transfers/patient-transfers-config.json, packages/esm-ugandaemr-app/src/views/hiv/hct/treatment/treatment-config.json
https://metsprogramme.atlassian.net/browse/U4X-948
=> U4X-948: Adjusting form names

packages/esm-ugandaemr-app/src/routes.json
https://metsprogramme.atlassian.net/browse/U4X-958
=> U4X-958: Removing the facility registry slot

packages/esm-ugandaemr-app/src/views/hiv/hct/family-tracking/family-tracking-config.json, packages/esm-ugandaemr-app/src/views/hiv/hct/patient-summary/patient-summary-baseline-information-config.json, packages/esm-ugandaemr-app/src/views/hiv/hct/patient-summary/patient-summary-hiv-monitoring-config.json, packages/esm-ugandaemr-app/src/views/hiv/hct/patient-summary/patient-summary-tpt-config.json, packages/esm-ugandaemr-app/src/views/hiv/hct/treatment/treatment-config.json
This PR fixes the date formats in the encounter tables for the different clinical views.
Before
After
https://metsprogramme.atlassian.net/browse/U4X-941
=> U4X-941 : Format Dates on Return Visit to a date

packages/esm-ugandaemr-app/src/custom-expressions/custom-apis.ts, packages/esm-ugandaemr-app/src/custom-expressions/custom-expressions.ts, packages/esm-ugandaemr-app/src/index.ts
https://metsprogramme.atlassian.net/browse/U4X-1048
https://github.com/user-attachments/assets/81938f0a-fed6-44f6-9c6d-77df168e6d93
=> U4X-1048: Adding back custom expressions to fetch DSD Groups

packages/esm-patient-queues-app/src/dashboard.meta.ts, packages/esm-patient-queues-app/src/root.component.tsx, packages/esm-ugandaemr-app/src/index.ts, packages/esm-ugandaemr-app/src/routes.json
This creates a home left nav that routes to home/initial-page
https://metsprogramme.atlassian.net/browse/U4X-1059
=> U4X-1059: Creating a home left nav
